// Code generated by MockGen. DO NOT EDIT.
// Source: ./route53.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	route53 "github.com/aws/aws-sdk-go/service/route53"
	gomock "github.com/golang/mock/gomock"
	types "github.com/openshift/installer/pkg/types"
	field "k8s.io/apimachinery/pkg/util/validation/field"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// GetBaseDomain mocks base method.
func (m *MockAPI) GetBaseDomain(ctx context.Context, baseDomainName string) (*route53.HostedZone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseDomain", ctx, baseDomainName)
	ret0, _ := ret[0].(*route53.HostedZone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBaseDomain indicates an expected call of GetBaseDomain.
func (mr *MockAPIMockRecorder) GetBaseDomain(ctx, baseDomainName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseDomain", reflect.TypeOf((*MockAPI)(nil).GetBaseDomain), ctx, baseDomainName)
}

// GetHostedZone mocks base method.
func (m *MockAPI) GetHostedZone(ctx context.Context, hostedZone string) (*route53.GetHostedZoneOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostedZone", ctx, hostedZone)
	ret0, _ := ret[0].(*route53.GetHostedZoneOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostedZone indicates an expected call of GetHostedZone.
func (mr *MockAPIMockRecorder) GetHostedZone(ctx, hostedZone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostedZone", reflect.TypeOf((*MockAPI)(nil).GetHostedZone), ctx, hostedZone)
}

// ValidateZoneRecords mocks base method.
func (m *MockAPI) ValidateZoneRecords(ctx context.Context, zone *route53.HostedZone, zoneName string, zonePath *field.Path, ic *types.InstallConfig) field.ErrorList {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateZoneRecords", ctx, zone, zoneName, zonePath, ic)
	ret0, _ := ret[0].(field.ErrorList)
	return ret0
}

// ValidateZoneRecords indicates an expected call of ValidateZoneRecords.
func (mr *MockAPIMockRecorder) ValidateZoneRecords(ctx, zone, zoneName, zonePath, ic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateZoneRecords", reflect.TypeOf((*MockAPI)(nil).ValidateZoneRecords), ctx, zone, zoneName, zonePath, ic)
}
